apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: webserver
    image: munwork/python-docker
    ports:
    - containerPort: 8093
  - name: webwatcher
    image: afakharany/watcher:latest
