apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: munwork/python-docker
    ports:
    - name: nodejs-port
      containerPort: 3000
